### ISSUE TITLE
Bug using LocalDate parameter to sql queries

### ISSUE THREAD

**Issue by airdrik** [sepatel/tekniq#1]
I found a rather obnoxious bug using tekniq-jdbc to do sql queries.  When passing a LocalDate as a parameter to the sql query, the resulting date ends up 1900 years in the future.
The reason being that the java.util.Date and java.sql.Date constructors which take the year, month and day assume the year is years since 1900 and add that many years to the date.

Instead, it is recommended to use java.sql.Date.valueOf(myLocalDate) instead (ref: line 80 of TqConnectionExt.kt)

**Comment by sepatel** [comment]
I've pushed up a fix onto a branch _fix-locatdatetime_, however it will probably be this weekend before I'm able to fully regression test everything and push up a release.

Thank you for discovering and providing a detailed explanation as to the issue and resolution.

**Comment by sepatel** [comment]
Fixed, validated, and released with version 0.9.6

**Comment by airdrik** [comment]
Looks good, thank you!
